[workspace]
members = [
    "crates/aw-abi",
    "crates/aw-core",
    "crates/aw-kernel",
    "crates/aw-storage",
    "boot/aw-uefi",
]
default-members = [
    "crates/aw-abi",
    "crates/aw-core",
    "crates/aw-kernel",
    "crates/aw-storage",
]
resolver = "3"

[workspace.package]
edition = "2024"
rust-version = "1.98.1"
version = "0.1.0"

[workspace.lints.rust]
missing_docs = "warn"
unsafe_op_in_unsafe_fn = "deny"

[workspace.lints.clippy]
all = "warn"
