//! Accessible hierarchical UEFI Setup owned by Accessible Windows.
//!
//! The firmware stage must remain operable without sight. This module therefore
//! keeps the whole Setup on the keyboard, emits deterministic proof markers for
//! every visible item and state transition, and never times out after the user has
//! interacted. Fixed speech phrases are generated by scripts/gen-speech.ps1 and
//! are wired into HDA separately so text-only navigation is never mistaken for
//! completed nonvisual speech.

use core::time::Duration;

use uefi::boot;
use uefi::proto::console::text::{Key, ScanCode};
use uefi::runtime::{self, ResetType};
use uefi::system;
use uefi::Status;

use crate::sound;

const IDLE_WINDOW: Duration = Duration::from_secs(3);
const POLL_INTERVAL: Duration = Duration::from_millis(50);
const CUE_MOVE_HZ: u32 = 660;
const CUE_ENTER_HZ: u32 = 784;
const CUE_BACK_HZ: u32 = 523;

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
enum Page {
    Root,
    Main,
    SystemInformation,
    Advanced,
    CpuConfiguration,
    Boot,
    BootPriorities,
    Security,
    SecureBoot,
    SaveExit,
    ConfirmRestart,
    ConfirmShutdown,
}

#[derive(Clone, Copy, Debug)]
enum Action {
    Enter(Page),
    Back,
    ContinueBoot,
    Restart,
    Shutdown,
    FirmwareSetupPending,
    Noop,
}

#[derive(Clone, Copy)]
struct MenuItem {
    label: &'static str,
    action: Action,
}

const ROOT_ITEMS: &[MenuItem] = &[
    MenuItem {
        label: "Main",
        action: Action::Enter(Page::Main),
    },
    MenuItem {
        label: "Advanced",
        action: Action::Enter(Page::Advanced),
    },
    MenuItem {
        label: "Boot",
        action: Action::Enter(Page::Boot),
    },
    MenuItem {
        label: "Security",
        action: Action::Enter(Page::Security),
    },
    MenuItem {
        label: "Save and Exit",
        action: Action::Enter(Page::SaveExit),
    },
];

const MAIN_ITEMS: &[MenuItem] = &[
    MenuItem {
        label: "System information",
        action: Action::Enter(Page::SystemInformation),
    },
    MenuItem {
        label: "Back",
        action: Action::Back,
    },
];

const SYSTEM_INFORMATION_ITEMS: &[MenuItem] = &[
    MenuItem {
        label: "Display resolution",
        action: Action::Noop,
    },
    MenuItem {
        label: "Firmware vendor",
        action: Action::Noop,
    },
    MenuItem {
        label: "Firmware revision",
        action: Action::Noop,
    },
    MenuItem {
        label: "UEFI specification revision",
        action: Action::Noop,
    },
    MenuItem {
        label: "Back",
        action: Action::Back,
    },
];

const ADVANCED_ITEMS: &[MenuItem] = &[
    MenuItem {
        label: "CPU configuration",
        action: Action::Enter(Page::CpuConfiguration),
    },
    MenuItem {
        label: "Back",
        action: Action::Back,
    },
];

const CPU_CONFIGURATION_ITEMS: &[MenuItem] = &[
    MenuItem {
        label: "Architecture x86 64",
        action: Action::Noop,
    },
    MenuItem {
        label: "Virtualization capability",
        action: Action::Noop,
    },
    MenuItem {
        label: "Back",
        action: Action::Back,
    },
];

const BOOT_ITEMS: &[MenuItem] = &[
    MenuItem {
        label: "Boot option priorities",
        action: Action::Enter(Page::BootPriorities),
    },
    MenuItem {
        label: "Boot normally",
        action: Action::ContinueBoot,
    },
    MenuItem {
        label: "Back",
        action: Action::Back,
    },
];

const BOOT_PRIORITIES_ITEMS: &[MenuItem] = &[
    MenuItem {
        label: "Current boot option",
        action: Action::Noop,
    },
    MenuItem {
        label: "Boot order",
        action: Action::Noop,
    },
    MenuItem {
        label: "Back",
        action: Action::Back,
    },
];

const SECURITY_ITEMS: &[MenuItem] = &[
    MenuItem {
        label: "Secure Boot",
        action: Action::Enter(Page::SecureBoot),
    },
    MenuItem {
        label: "Back",
        action: Action::Back,
    },
];

const SECURE_BOOT_ITEMS: &[MenuItem] = &[
    MenuItem {
        label: "Secure Boot state",
        action: Action::Noop,
    },
    MenuItem {
        label: "Setup mode",
        action: Action::Noop,
    },
    MenuItem {
        label: "Back",
        action: Action::Back,
    },
];

const SAVE_EXIT_ITEMS: &[MenuItem] = &[
    MenuItem {
        label: "Boot normally",
        action: Action::ContinueBoot,
    },
    MenuItem {
        label: "Enter firmware setup",
        action: Action::FirmwareSetupPending,
    },
    MenuItem {
        label: "Restart",
        action: Action::Enter(Page::ConfirmRestart),
    },
    MenuItem {
        label: "Shut down",
        action: Action::Enter(Page::ConfirmShutdown),
    },
    MenuItem {
        label: "Back",
        action: Action::Back,
    },
];

const CONFIRM_RESTART_ITEMS: &[MenuItem] = &[
    MenuItem {
        label: "Confirm restart",
        action: Action::Restart,
    },
    MenuItem {
        label: "Cancel",
        action: Action::Back,
    },
];

const CONFIRM_SHUTDOWN_ITEMS: &[MenuItem] = &[
    MenuItem {
        label: "Confirm shut down",
        action: Action::Shutdown,
    },
    MenuItem {
        label: "Cancel",
        action: Action::Back,
    },
];

fn items(page: Page) -> &'static [MenuItem] {
    match page {
        Page::Root => ROOT_ITEMS,
        Page::Main => MAIN_ITEMS,
        Page::SystemInformation => SYSTEM_INFORMATION_ITEMS,
        Page::Advanced => ADVANCED_ITEMS,
        Page::CpuConfiguration => CPU_CONFIGURATION_ITEMS,
        Page::Boot => BOOT_ITEMS,
        Page::BootPriorities => BOOT_PRIORITIES_ITEMS,
        Page::Security => SECURITY_ITEMS,
        Page::SecureBoot => SECURE_BOOT_ITEMS,
        Page::SaveExit => SAVE_EXIT_ITEMS,
        Page::ConfirmRestart => CONFIRM_RESTART_ITEMS,
        Page::ConfirmShutdown => CONFIRM_SHUTDOWN_ITEMS,
    }
}

fn title(page: Page) -> &'static str {
    match page {
        Page::Root => "Accessible Windows firmware setup",
        Page::Main => "Main",
        Page::SystemInformation => "System information",
        Page::Advanced => "Advanced",
        Page::CpuConfiguration => "CPU configuration",
        Page::Boot => "Boot",
        Page::BootPriorities => "Boot option priorities",
        Page::Security => "Security",
        Page::SecureBoot => "Secure Boot",
        Page::SaveExit => "Save and Exit",
        Page::ConfirmRestart => "Confirm restart",
        Page::ConfirmShutdown => "Confirm shut down",
    }
}

fn parent(page: Page) -> Page {
    match page {
        Page::Root => Page::Root,
        Page::Main | Page::Advanced | Page::Boot | Page::Security | Page::SaveExit => Page::Root,
        Page::SystemInformation => Page::Main,
        Page::CpuConfiguration => Page::Advanced,
        Page::BootPriorities => Page::Boot,
        Page::SecureBoot => Page::Security,
        Page::ConfirmRestart | Page::ConfirmShutdown => Page::SaveExit,
    }
}

fn poll_key() -> Option<Key> {
    system::with_stdin(|stdin| stdin.read_key().unwrap_or(None))
}

fn render(page: Page, selected: usize, width: usize, height: usize) {
    let _ = system::with_stdout(|stdout| stdout.clear());
    uefi::println!("{}", title(page));
    uefi::println!();
    uefi::println!("  Up/Down or Tab: move. Enter: open/activate. Escape: back.");
    uefi::println!();

    for (index, item) in items(page).iter().enumerate() {
        let prefix = if index == selected { ">" } else { " " };
        uefi::println!("{prefix} {}", item.label);
        log::info!(
            "AW_UEFI_MENU_ITEM page={:?} index={} selected={} label=\"{}\"",
            page,
            index,
            index == selected,
            item.label
        );
    }

    log_values(page, selected, width, height);
}

fn log_values(page: Page, selected: usize, width: usize, height: usize) {
    match (page, selected) {
        (Page::SystemInformation, 0) => {
            log::info!(
                "AW_UEFI_SETUP_VALUE name=display value={}x{}",
                width,
                height
            );
        }
        (Page::SystemInformation, 1) => {
            log::info!("AW_UEFI_SETUP_VALUE name=firmware_vendor available=true");
        }
        (Page::SystemInformation, 2) => {
            log::info!(
                "AW_UEFI_SETUP_VALUE name=firmware_revision value={}",
                system::firmware_revision()
            );
        }
        (Page::SystemInformation, 3) => {
            log::info!("AW_UEFI_SETUP_VALUE name=uefi_revision available=true");
        }
        (Page::CpuConfiguration, 0) => {
            log::info!("AW_UEFI_SETUP_VALUE name=architecture value=x86_64");
        }
        (Page::CpuConfiguration, 1) => {
            log::info!(
                "AW_UEFI_SETUP_VALUE name=virtualization value=firmware_controlled"
            );
        }
        (Page::BootPriorities, 0) => {
            log::info!(
                "AW_UEFI_SETUP_VALUE name=boot_current value=pending_dynamic_read"
            );
        }
        (Page::BootPriorities, 1) => {
            log::info!("AW_UEFI_SETUP_VALUE name=boot_order value=pending_dynamic_read");
        }
        (Page::SecureBoot, 0) => {
            log::info!(
                "AW_UEFI_SETUP_VALUE name=secure_boot value=pending_dynamic_read"
            );
        }
        (Page::SecureBoot, 1) => {
            log::info!("AW_UEFI_SETUP_VALUE name=setup_mode value=pending_dynamic_read");
        }
        _ => {}
    }
}

fn announce_focus(page: Page, selected: usize, width: usize, height: usize) {
    let item = &items(page)[selected];
    log::info!(
        "AW_UEFI_SETUP_FOCUS page={:?} index={} label=\"{}\"",
        page,
        selected,
        item.label
    );
    log_values(page, selected, width, height);
}

fn move_selection(page: Page, selected: usize, delta: i8) -> usize {
    let count = items(page).len();
    if count == 0 {
        return 0;
    }
    if delta < 0 {
        if selected == 0 {
            count - 1
        } else {
            selected - 1
        }
    } else {
        (selected + 1) % count
    }
}

fn activate(page: &mut Page, selected: &mut usize, width: usize, height: usize) -> bool {
    let item = items(*page)[*selected];
    match item.action {
        Action::Enter(next) => {
            *page = next;
            *selected = 0;
            sound::cue(CUE_ENTER_HZ, Duration::from_millis(45));
            log::info!("AW_UEFI_SETUP_ACTION action=open page={:?}", next);
            render(*page, *selected, width, height);
            announce_focus(*page, *selected, width, height);
        }
        Action::Back => {
            *page = parent(*page);
            *selected = 0;
            sound::cue(CUE_BACK_HZ, Duration::from_millis(45));
            log::info!("AW_UEFI_SETUP_ACTION action=back page={:?}", *page);
            render(*page, *selected, width, height);
            announce_focus(*page, *selected, width, height);
        }
        Action::ContinueBoot => {
            log::info!("AW_UEFI_SETUP_ACTION action=boot_normally reason=user");
            log::info!("AW_UEFI_SETUP_PROOF_OK");
            return true;
        }
        Action::Restart => {
            log::info!("AW_UEFI_SETUP_ACTION action=restart confirmed=true");
            runtime::reset(ResetType::COLD, Status::SUCCESS, None);
        }
        Action::Shutdown => {
            log::info!("AW_UEFI_SETUP_ACTION action=shutdown confirmed=true");
            runtime::reset(ResetType::SHUTDOWN, Status::SUCCESS, None);
        }
        Action::FirmwareSetupPending => {
            log::warn!(
                "AW_UEFI_SETUP_ACTION action=firmware_setup status=pending_standard_os_indications"
            );
        }
        Action::Noop => {
            announce_focus(*page, *selected, width, height);
        }
    }
    false
}

/// Run the accessible Setup before ExitBootServices.
///
/// With no input, the root menu remains visible for a short deterministic window
/// and then boots normally. Once any key is received, the timeout is permanently
/// disabled for this boot, so a person navigating nonvisually is never raced by
/// an automatic boot.
pub fn run(width: usize, height: usize) {
    log::info!("AW_UEFI_SETUP_BEGIN");

    let mut page = Page::Root;
    let mut selected = 0usize;
    let mut interacted = false;
    let mut waited = Duration::ZERO;

    render(page, selected, width, height);
    announce_focus(page, selected, width, height);
    log::info!("AW_UEFI_SETUP_READY");

    loop {
        if let Some(key) = poll_key() {
            interacted = true;
            match key {
                Key::Special(ScanCode::DOWN) => {
                    selected = move_selection(page, selected, 1);
                    sound::cue(CUE_MOVE_HZ, Duration::from_millis(30));
                    render(page, selected, width, height);
                    announce_focus(page, selected, width, height);
                }
                Key::Special(ScanCode::UP) => {
                    selected = move_selection(page, selected, -1);
                    sound::cue(CUE_MOVE_HZ, Duration::from_millis(30));
                    render(page, selected, width, height);
                    announce_focus(page, selected, width, height);
                }
                Key::Special(ScanCode::ESCAPE) => {
                    if page == Page::Root {
                        log::info!(
                            "AW_UEFI_SETUP_ACTION action=boot_normally reason=escape_root"
                        );
                        log::info!("AW_UEFI_SETUP_PROOF_OK");
                        return;
                    }
                    page = parent(page);
                    selected = 0;
                    sound::cue(CUE_BACK_HZ, Duration::from_millis(45));
                    log::info!("AW_UEFI_SETUP_ACTION action=back page={:?}", page);
                    render(page, selected, width, height);
                    announce_focus(page, selected, width, height);
                }
                Key::Printable(character) => match char::from(character) {
                    '\r' => {
                        if activate(&mut page, &mut selected, width, height) {
                            return;
                        }
                    }
                    '\t' => {
                        selected = move_selection(page, selected, 1);
                        sound::cue(CUE_MOVE_HZ, Duration::from_millis(30));
                        render(page, selected, width, height);
                        announce_focus(page, selected, width, height);
                    }
                    _ => {}
                },
                Key::Special(_) => {}
            }
            continue;
        }

        if !interacted {
            if waited >= IDLE_WINDOW {
                log::info!("AW_UEFI_SETUP_ACTION action=boot_normally reason=timeout");
                log::info!("AW_UEFI_SETUP_PROOF_OK");
                return;
            }
            waited += POLL_INTERVAL;
        }
        boot::stall(POLL_INTERVAL);
    }
}
